export const CART_ACTION_TYPES = {
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_ITEM: "CLEAR_ITEM",
  TOGGLE_CART: "TOGGLE_CART",
  UPDATE_TOTAL_QUANTITY: "UPDATE_TOTAL_QUANTITY",
  // UPDATE_TOTAL_PRICE: "UPDATE_TOTAL_PRICE",
  // CLEAR_CART: "CLEAR_CART",
};
